[project]
name = "codereviewer-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=3.6.0",
    "peft>=0.15.2",
    "transformers>=4.52.3",
]
